[package]
name = "processing"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.152"
numass = { git = "https://bitbucket.org/Kapot/dataforge-parser-numass.git", tag = "0.1.2" }

egui = { version = "0.21.0", optional = true }
plotly = { version = "0.8.3", optional = true }

[features]
egui = ["dep:egui"]
plotly = ["dep:plotly"]

[patch."https://bitbucket.org/Kapot/dataforge-parser-numass.git"]
numass = { path = "../dataforge-parser-numass" }